### ISSUE TITLE
389 failed to install nsz

### ISSUE THREAD

**Issue by scturtle** [rashevskyv/dbi#119]
zstd decompression error
368 is ok

**Comment by rashevskyv** [comment]
Should provide more info

ср, 3 серп. 2022, 20:39 користувач scturtle ***@***.***> пише:

**Comment by scturtle** [comment]
The latest DBI version 389 cannot install game with nsz format via "Browser SD card"/"Browse USB0 Drive" mode. The error message is "ZSTD DECOMPRESSION ERROR". MTP mode is OK. I've tried many files and here is an [example](https://kaifa520.sharepoint.com/sites/switch520.com6/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fswitch520%2Ecom6%2FShared%20Documents%2F2022%E5%B9%B4%2D07%E6%9C%88%2DGAME%2F%5B%E5%9B%9B%E6%B5%B7%E6%97%85%E4%BA%BA%5D%2EAs%20Far%20As%20The%20Eye&p=true&ga=1). DBI 368 is just fine.

**Comment by djakkk** [comment]
I just updated to 389 and got the same problem.
I also tried 386 and found that the problem seems to be introduced in 386.

Going back to 368 solved the problem and the game installed correctly.
This is via USB0,

![IMG_9130](https://user-images.githubusercontent.com/44234155/185762709-d8c90e89-34d1-45ee-ba53-b7c1e23ff316.jpg)

**Comment by rashevskyv** [comment]
Launch dbi from hbl's title mode

**Comment by djakkk** [comment]
> Launch dbi from hbl's title mode

The installation worked perfect i full memory mode, I'm so used to running dbi in applet-mode so I didn't think of trying that.

Thanks for your help and an excellent program.
