### ISSUE TITLE
How can I install games with http?

### ISSUE THREAD

**Issue by lesca** [rashevskyv/dbi#21]
I cannot find any option related from the main menu.

How can I use http? I only find you mentioned "http" in readme but no more details ...

**Comment by rashevskyv** [comment]
The "Network repo" item appears when there is a dbi.network.config file next to the dbi.nro program

To install games over the network, edit the included dbi.network.config file, changing the IP address 127.0.0.1 to your PC (server):
`ApacheHTTP | Network repo | http: //127.0.0.1/Nintendo/Switch/`

Save and copy it to the /switch/ folder on the microSD.

Then unzip the included nginx.zip archive on your PC (you can also use any other HTTP server with DirectoryListing enabled: Apache, Mongoose, Python SimpleHTTP, sheret, rclone, etc.), edit the /nginx/conf/nginx.conf file, in the 48th line, instead of 127.0.0.1, enter the IP address of the console (or your entire subnet like 192.168.1.1/24 or 192.168.0.0/16); it can be found on Switch in System Preferences> Internet:

```worker_processes 1;

events {
worker_connections 1024;
}

http {
include mime.types;
default_type application/octet-stream;

sendfile on;

keepalive_timeout 65;

server {
listen 80;
server_name localhost;

location / {
root html;
index index.html index.htm;
}
location /Nintendo/Switch/ {
allow 127.0.0.1;
deny all;
autoindex on;
}

error_page 500 502 503 504 /50x.html;
location = /50x.html {
root html;
}

}

}

**Comment by xadox-1st** [comment]
Is there still somewhere the nginx.zip? @rashevskyv

**Comment by laleeroy** [comment]
Hello, anyone of you have a detailed guide to set this up?
