### ISSUE TITLE
Install NSP with any name

### ISSUE THREAD

**Issue by toxic9** [rashevskyv/dbi#78]
Hi!

I noticed NSP's need to have a standard name to procceed the installation.

Example: "Game Name [0100000000010000] [v65536].nsp"

I can't install "Game Name.nsp".

Maybe it has something to do with special characters like "é" on Pok**é**mon  ??

**Comment by duckbill007** [comment]
Not reproducible. Just installed "Game Name.nsp".

**Comment by toxic9** [comment]
I tried Pokémon.nsp and when you click on button A to start the installation it does nothing

**Comment by rashevskyv** [comment]
Special characters are supported. Provide screenshots

**Comment by toxic9** [comment]
![IMG-20211213-WA0018](https://user-images.githubusercontent.com/34398680/145886875-94e0fac1-d501-4a9c-9e1f-48084dc33dca.jpg)


As you can see not all special characters are allowed.

**Comment by FlyingBananaTree** [comment]
It's not a DBI issue- this is happening because you're circumventing DBI and transferring the file to your SD card when the OS isn't live, the Switch's filesystem can't actually handle those characters.

The solution is to install with DBI's MTP, USB (dbibackend), external USB drive. DBI will skip/ignore the characters with no issue. There's no particular reason to be installing the way you are these days but if you really want to do that then rename the file first.

**Comment by toxic9** [comment]
I put the SD card on my PC and copy paste it. I'm not sending it to the switch by any protocol.
Thanks anyway!

**Comment by Masamune3210** [comment]
That's what they are saying. If you are manually adding the files to the SD card through some way other than through the switch you have to make sure the filenames are plain text, no special chars
